sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: yTaJ4/TfJiqcBSzOr3OSDQxdm3giWJoYERqtTfzYtIJWj3v40YMPoXsxQ/4lWrLUyIFXDj268O0sJmw7qKC6NzId1Ixc+RmxqEDKveMrslU8aiaPNdI9VRZKm772+CPbSMLuB+CoBFJ9uvqlGDR4yP+I38KT9dX7s03ZojmM1AoyPoF8IcVmAS9rERvrH9oiUx9peuRkh9MPtMOa76eN+XaHXqo1DXiN2RQDc0MpxdXw9jGSMY1kIQmgicAzIWHUPD0PlBC6WUZAOkYb12XQ0dgkTpTF5R9Jr7U06vj5AU3kJ8Htcds4tLHC/GsBKUNeiAv4z8Hc7qqgTNOU2a2qyiPRxO6VFuvvoDxVoUE0xyxt72EtQAsnHdl2k4cX0oJriMJv/rot61oVqA+tuN7Lk2mGltzCRG99n861ehb9KvPF87kmDoP7zOZ0LzXDoSUOoMeVCndNv2zeh/sucIeHwarraBdKWtPfvwSLaV0N2KyT28CRywttmz0SO8EdpGLg64NQ7RhnRZGlVRtgOdZf2i3LqbUDbFajYvPH/7oYTWPIQytT2kfTPKv7nLedS7TeUJTuzP4TGOM2m4FYpDx4d75qvHB9NVLivd71zw4ozblO6yY2uxsHJyHKTv1Bdrc4GRFQzbj4BIi6PkAnCKrObaNWB+VNP6odvH7dVNnDOkU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Jenseits-der-Schriftkultur---Band-4_4374
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy